#!/bin/sh -ex

GIT_SEMVER_ARGS=""

if [ -f $(git rev-parse --git-dir)/shallow ]; then
  echo "Shallow repositories are not supported! Please checkout with fetch-depth 0."
  exit 1
fi

if [ "${INCLUDE_PRE_RELEASES}" == "true" ]; then
  GIT_SEMVER_ARGS="--include-pre-releases"
fi

if [ ! -z "${MAJOR_VERSION}" ] && [ "${MAJOR_VERSION}" != "latest" ]; then
  GIT_SEMVER_ARGS="${GIT_SEMVER_ARGS} --major-version=${MAJOR_VERSION}"
fi

echo "::set-output name=version::$(git-semver latest ${GIT_SEMVER_ARGS})"
