#!/bin/sh -ex

LATEST_VERSION="$(git semver latest)"

if [ -f $(git rev-parse --git-dir)/shallow ]; then
  echo "Shallow repositories are not supported! Please checkout with fetch-depth 0."
  exit 1
fi

NEXT_VERSION="$(git semver next)"
echo "version=${NEXT_VERSION}" >> $GITHUB_OUTPUT
