#!/bin/sh -ex

if [ -f $(git rev-parse --git-dir)/shallow ]; then
  echo "Shallow repositories are not supported! Please checkout with fetch-depth 0."
  exit 1
fi

GIT_SEMVER_ARGS=""

if [ "${EXCLUDE_PRE_RELEASES}" == "true" ]; then
  GIT_SEMVER_ARGS="--exclude-pre-releases"
fi

if [ ! -z "${VERSION}" ] && [ "${VERSION}" != "next" ]; then
  GIT_SEMVER_ARGS="${GIT_SEMVER_ARGS} ${VERSION}"
fi

CHANGELOG="$(git-semver log ${GIT_SEMVER_ARGS} --markdown)"
CHANGELOG="${CHANGELOG//'%'/'%25'}"
CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"

echo "::set-output name=changelog::${CHANGELOG}"
